[package]
name = "collection_macro"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
description = "General-purpose `seq![]` and `map! {}` collection macros"

[dev-dependencies]
mitsein = "0.7"
